name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install packages && run lint
        run: yarn

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.remote_host  }}
          username: ${{ secrets.remote_user }}
          password: ${{ secrets.remote_pass }}
          port: ${{ secrets.remote_port }}
          script: |
            whoami
            echo "$HOST"
            ls -al
